#pragma once
#include <cmath>
#include "GLFW/glfw3.h"
#include "raylib.h"
#include "characterWalk.h"
#include "muscularSystem.h"
#include "skeletalSystem.h"
#include "organSystem.h"
#include "nerveSystem.h"
#include "main.h"
